### PR TITLE
EZP-25414 Fixed zone clone

### PR DESCRIPTION
**Pull request by hgiesenow**
Link: https://jira.ez.no/browse/EZP-25414

### CODE REVIEW

**Comment by bdunogier** [comment]
Hi, and thank you for the PR. It looks good to me.

Ping @yannickroger @lserwatka.

**Comment by lserwatka** [comment]
+1

**Comment by yannickroger** [comment]
This PR should be opened against https://github.com/ezsystems/ezflow
This one is read only for composer distribution.

**Comment by bdunogier** [comment]
Was a new PR opened against ezsystems/ezflow ? I can't see anything over there.

**Pull request closed without merging**
