### PR TITLE
Inject block into custom-fetchers.

### PR DESCRIPTION
**Pull request by annitya**
I need all the data provided by the block.

### CODE REVIEW

**Comment by andrerom** [comment]
You'll unfortunately need to open this against https://github.com/ezsystems/ezflow, this is a read only git repo.

But before you do, @lserwatka would this be ok?

**Comment by andrerom** [comment]
@lserwatka there was a question above ;)

**Comment by lserwatka** [comment]
@andrerom we spoke on Slack about it :) A slightly changed approach will be added as PR to ezflow repo.

**Comment by andrerom** [comment]
Ok perfect,  but as slack is volatile communication, let's keep conclusions here/jira :)

**Pull request closed without merging**
